image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - tags
  script:
    - npm config set @raftmodding:registry https://gitlab.com/api/v4/projects/22054232/packages/npm/
    - npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm config set '//gitlab.com/api/v4/projects/22054232/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm install
    - npm run build
    - npm publish